{
 "title": "TechStore - Uygulama Metrikleri",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ä°stek HÄ±zÄ± (Dakikada)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "p95 Ä°stek SÃ¼resi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "En PopÃ¼ler ÃœrÃ¼nler (Sepete Ekleme)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "topk(5, cart_add_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "5xx Hata OranÄ±",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{status=~\"5..\"}[5m])) or vector(0))\r\n/\r\n(sum(rate(http_requests_total[5m])) > 0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}